### DISCUSSION TITLE
Initial Plot Seek Speed on Large Farms

### DISCUSSION THREAD

**Discussion by antonmakarenko** [Chia-Network/chia-blockchain#11018] [Ideas]
Given: a 1.5PiB farm with 15000+ plots scattered around ~100 disks. Each disk is mounted in a directory and the directory is configured in `config.yaml`.

Config settings look like so:
```
harvester:
  plot_directories:
  - /mnt/a
  - /mnt/b
  - /mnt/c
  - ...
  - ...
  plots_refresh_parameter:
    batch_size: 300
    batch_sleep_milliseconds: 1
    interval_seconds: 120
    retry_invalid_seconds: 1200
```

It takes a long time to start up such a farm. When observing `debug.log`, one may conclude that there is just a single thread of collecting plot files.

Would it be possible to spawn multiple threads in this case? What if we add a new parameter in the `plots_refresh_parameter` section, something like:
```
initial_threads: 4
```
And for each of the defined directories, spawn a new plot seek thread, limiting number of threads to be run at a time to the specified number? Wouldn't it theoretically increase initialization time 4x?
