### DISCUSSION TITLE
in 24 hours ，12p  storage get one block reward ,pls help me

### DISCUSSION THREAD

**Discussion by ben00007** [Chia-Network/chia-blockchain#4784] [Support]
I'm solo mining, but my storage power doesn't match the proportion of my blasting block

I have 12p storage, which is distributed on 2500 machines, but today I only have one burst in 24 hours. Chia is deploying version 1.1.5.

My deployment plan is a reference

https://github.com/Chia-Network/chia-blockchain/wiki/Farming-on-many-machines Document deployment.

Because I have many machines and they are distributed in different areas, I have deployed three main machines (farmers), and other harvesters are connected to the main machine respectively,

There are no other warning and error messages in debug.log, and the messages between farmer and harvester are normal.

Is it feasible to deploy three main machines (farmers) in one wallet? If this scheme is feasible, how can I confirm that the whole mining is working normally?

Looking forward to your reply, thank you!

**Comment by ben00007** [comment]
The day before yesterday, when I had 7p storage computing power, it was deployed according to a full node wallet. There were 1300 machines connected to a full node wallet. In 24 hours, we won 9 pieces of reward. But now, when we had 12p storage computing power, there were 2500 machines connected to three full node main machians, and they were all the same wallet. We only got a reward of one block in 24 hours.

**Reply by ghost** [reply]
Wow, impressive scale for a solo miner! Looks like it's already impossible to participate as a SOHO farmer.

I would raise the log-level on the harvester and validate the turnaround time.

```
harvester:                                                                                                       
  chia_ssl_ca:                                                                                                   
    crt: config/ssl/ca/chia_ca.crt                                                                               
    key: config/ssl/ca/chia_ca.key                                                                               
    port: 8446                                                                                                   
  wallet_peer:                                                                                                   
    host: 127.0.0.1                                                                                              
  farmer_peer:                                                                                                   
    host: 127.0.0.1                                                                                              
    port: 8447                                                                                                   
  logging:                                                                                                       
    log_filename: log/harvester.log
    log_level: INFO
    log_maxfilesrotation: 7
    log_stdout: false
```
