### DISCUSSION TITLE
Is there a way to connect a wallet to a remote full node?

### DISCUSSION THREAD

**Discussion by thomann061** [Chia-Network/chia-blockchain#5150] [Q&A]
I am using ubuntu, and I am wondering if there is a way to run the wallet-only, and connect the wallet to a remote full node.

**Comment by gklech** [comment]
Hi.
I have the same question. In my home network I have full synced node and on other machine I'd like to have synced wallet. In config.yaml I tried to set properties for wallet section:
```
wallet:
  full_node_peer:
    host: IP_of_my_local_fully_synced_node
    port: 8444
```
 but wallet still no synced. Maybe there are other settings in config.yaml to change that I'm unaware??
