### DISCUSSION TITLE
making chia esay install by ansible

### DISCUSSION THREAD

**Discussion by huang12zheng** [Chia-Network/chia-blockchain#6718] [Ideas]
update install.sh with add parm -S to sudo
```yaml
- name: Chia Install
  # become: true
  shell:
    chdir: /opt/chia-blockchain
    # creates: /opt/chia-blockchain/activate
    cmd: |
      chmod a+x install.sh
      echo {{ansible_ssh_pass}} |sh install.sh
```
`install.sh`
```sh
if [ "$UBUNTU" = "true" ] && [ "$UBUNTU_PRE_2004" = "1" ]; then
		# Ubuntu
		echo "Installing on Ubuntu pre 20.04 LTS."
		sudo apt-get update
		sudo apt-get install -y python3.7-venv python3.7-distutils
	elif [ "$UBUNTU" = "true" ] && [ "$UBUNTU_PRE_2004" = "0" ] && [ "$UBUNTU_2100" = "0" ]; then
		echo "Installing on Ubuntu 20.04 LTS."
		sudo -S apt-get update. #<<<<<<
		sudo -S apt-get install -y python3.8-venv python3-distutils #<<<<<<
	elif [ "$UBUNTU" = "true" ] && [ "$UBUNTU_2100" = "1" ]; then
		echo "Installing on Ubuntu 21.04 or newer."
		sudo apt-get update
		sudo apt-get install -y python3.9-venv python3-distutils
```
