### DISCUSSION TITLE
Usage of syslog

### DISCUSSION THREAD

**Discussion by ghost** [Chia-Network/chia-blockchain#7240] [Show and tell]
Hi all

Starting with Chia version 1.2.0 you'll be able to send the logs to a syslog server.
I plan to use it to be alerted in case the farmer runs into severe issues.

### Enable syslog

Edit ~/.chia/mainnet/config.yaml
Set farmer.logging.log_syslog to true
Optionally change farmer.logging.log_syslog_host (default: localhost) and farmer.logging.log_syslog_port (default: 514)

```
farmer:
  full_node_peer:
    host: localhost
    port: 8444
  harvester_peer:
    host: localhost
    port: 8448
  logging: &id001
    log_filename: log/debug.log
    log_level: INFO
    log_maxfilesrotation: 7
    log_stdout: false
    log_syslog: true
    log_syslog_host: syslog.local
    log_syslog_port: 5144
```

### Synology Log Center

Synology's [Log Center](https://kb.synology.com/en-global/DSM/help/DSM/LogCenter/logcenter_desc) is available in the Package Center

**Specify a Log Receiving rule**
![Screenshot 2021-07-08 at 18 03 06](https://user-images.githubusercontent.com/35364122/124954959-ed4bc400-e016-11eb-8c5b-21258a83762b.png)

**Browse and search logs**
![Screenshot 2021-07-08 at 18 05 06](https://user-images.githubusercontent.com/35364122/124955183-27b56100-e017-11eb-9962-8428fdb233d0.png)

**Specify Notification rules**
![Screenshot 2021-07-08 at 18 06 38](https://user-images.githubusercontent.com/35364122/124955455-5c291d00-e017-11eb-9b13-2b44db508734.png)

### ELK Stack

More sophisticated installations could analyse log using the [ELK stack](https://www.elastic.co/what-is/elk-stack).
