### DISCUSSION TITLE
1.2.5 not showing new plots

### DISCUSSION THREAD

**Discussion by Meep1264** [Chia-Network/chia-blockchain#8257] [Support]
Plots not showing in farmer or pool plot tab. Please help

**Comment by loppefaaret** [comment]
1.2.4 brought in new settings in `config.yaml` that you might need to add manually:
```
  plots_refresh_parameter:
    batch_size: 30
    batch_sleep_milliseconds: 10
    interval_seconds: 120
```
under the `harvester:` section, just under the last of your plot entries, just above the port number... 
make sure you adheere to the indentation, 2 spaces infront of the first entry, and 4 spaces the the 3 following sub entries!
