### DISCUSSION TITLE
Configure farmer-only at home and full-node on VPS

### DISCUSSION THREAD

**Discussion by Ealrann** [Chia-Network/chia-blockchain#8499] [Support]
Hello,

My internet connection is slow (something like 10Mb/s), and running a full node makes it bad (regular ping spikes). 
So I'm trying to put the full node on a VPS, and keep the farmer/harvesters at home. 

The configuration looks rather simple:

```
# Home Farmer
farmer:
  full_node_peer:
    host: <vps address>
    port: 8444
```

```
# VPS node
full_node:
  farmer_peer:
    host: <home address>
    port: 8447
```

So far, so good, but it's too early to be sure everything is working.

Here my questions:
1. In this situation, who needs the private key? I guess definitely the Farmer, but what about the Full node? 
2. Is an up-to-date wallet necessary to farm with plotnft? if so, where (farmer side or node side?)
3. Configuring the farmer address in the full node configuration looks not necessary. Is there any benefit doing it? Would the full node prioritize this farmer, or something like that?
4. Does anyone made a similar configuration? Any tip?
