### DISCUSSION TITLE
How to move .chia folder to another drive

### DISCUSSION THREAD

**Discussion by Coci13** [Chia-Network/chia-blockchain#9596] [Support]
Hello, 

My PC can't work properly because my C drive is 100% used. How can i move the .chia folder to another drive?
I tried moving with mklink via the CMD, but it gives me an error "Cannot move the file when already exists" which it doesn't exist. 
Any solutions?

**Comment by marssystems** [comment]
I think we would all benefit from a step by step  "How to Guide" on this.

**Comment by SlugFiller** [comment]
https://github.com/Chia-Network/chia-blockchain/issues/7080#issuecomment-874304772

**Comment by Jacek-ghub** [comment]
You can modify your config.yaml as follow:
```
full_node:
  database_path: NEW_FULL_BLOCKCHAIN_PATH/blockchain_v1_CHALLENGE.sqlite
  peer_db_path: NEW_FULL_BLOCKCHAIN_PATH/peer_table_node.sqlite

wallet:
  database_path: NEW_FULL_WALLET_PATH/blockchain_wallet_v1_CHALLENGE_KEY.sqlite
  wallet_peers_path: NEW_FULL_WALLET_PATH/wallet_peers.sqlite

```
You may also consider moving your log file (especially, if your new drive is faster):
```
farmer:
  logging: &id001
    log_filename: NEW_FULL_LOG_PATH/debug.log

```
