### DISCUSSION TITLE
Reduce memory use - control multiple instances of chia_full_node

### DISCUSSION THREAD

**Discussion by caeci11ius** [Chia-Network/chia-blockchain#9914] [Ideas]
Is there some way to reduce the number of instances of chia_full_node that are running? I seem to have four by default and there doesn't seem to be a way to limit this. Could someone advise if it's possible to reduce, or if having four instances of chia_full_node is strictly necessary for farming to work? Ideally, I'd like to reduce this to two, or even one instance.

I'm running it on an older system with only 4GB of RAM, and it basically eats the entire memory capacity of the system. Since I've disabled the wallet and enabled zswap, I'm at least now avoiding very heavily smashing swap, but it would be good to use less RAM still. This would also help people running on 4GB Raspberry Pi 4s (the swap performance there is very poor, so it's probably really damaging overall system performance).

Top output (prior to disabling wallet - though ideally I'd like to get that back so I can get stats from plotnft show):

```
%CPU %MEM COMMAND
5.3  25.6 chia_full_node
0.0  24.4 chia_full_node
0.0  20.3 chia_wallet
0.0  20.2 chia_full_node
0.0  19.6 chia_full_node
0.0   1.0 chia_farmer
0.0   0.9 chia_harvester
```

**Comment by PVLPM** [comment]
I am also issuing the same problem. I have from 17 instances of chia_full_node, each 1.1GiB, so chia eats up to 20GiB of RAM which is crazy! Still couldn't find a fix.
@hoffmang9 @Yostra @mariano54 we need your help. I have a lot of system freezes which affect my farming income. Thank you!

**Reply by mariano54** [reply]
What version of the software are you running and what OS?
In main we have added a config parameter reserved cores, the higher you make this number, the less sub processes will be created:
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/util/initial-config.yaml#L346

Still it is very strange that each process is using so much, that is not expected behavior.

**Reply by PVLPM** [reply]
Thank you for your response.
I am using the latest version on Ubuntu 20.04. I just updated it recently (`Successfully installed chia-blockchain-1.2.11`), I am updating the chia-blockchain every week (if there are new updates), hoping that RAM problem will be fixed. 
I have 10700 (16 threads), so what would be optimal value to set in `reserved_cores:`? Will be `reserved_cores: 15` enough to keep up with full node?

**Comment by arvidn** [comment]
Since the processes may share pages, looking at [PSS](https://en.wikipedia.org/wiki/Proportional_set_size) might be more relevant than [RSS](https://en.wikipedia.org/wiki/Resident_set_size)

**Reply by PVLPM** [reply]
Here is my USS, PSS and RSS usages got from `smem`:
```
PID     User      Command                    Swap        USS      PSS      RSS
10895 invader  chia_full_node                     0    11404    77653  1106232 
10896 invader  chia_full_node                     0    11468    77677  1106184 
10894 invader  chia_full_node                     0    12108    78108  1106184 
10903 invader  chia_full_node                     0    13152    78931  1106184 
10902 invader  chia_full_node                     0    13452    79165  1106180 
10906 invader  chia_full_node                     0    14768    80291  1106176 
10897 invader  chia_full_node                     0    14828    80384  1106180 
10900 invader  chia_full_node                     0    15108    80615  1106260 
10907 invader  chia_full_node                     0    15600    81056  1106256 
10898 invader  chia_full_node                     0    16408    81792  1106240 
10901 invader  chia_full_node                     0    16692    82036  1106244 
10899 invader  chia_full_node                     0    16756    82096  1106188 
10886 invader  chia_full_node                     0     9696    82302  1102272 
10904 invader  chia_full_node                     0    17060    82377  1106172 
10885 invader  chia_full_node                     0     9968    82549  1102272 
10905 invader  chia_full_node                     0    24624    89456  1105980
```
Still uses a lot as I understand.

**Comment by caeci11ius** [comment]
Ubuntu 21.10
Chia (offical Docker container) v1.2.11

Interestingly I have four instances despite having 2 CPU cores and no hyperthreading in this machine...

This install has been running for several months, so the config.yaml is quite old (i'd guess installed around the point 1.2.8 was current?). It's nice to see the new version is so much better documented (and it has a lot of new useful options!). I'm guessing there's no easy way to regenerate the config while retaining the configured options (particularly for payments...I know it's easy enough to move them over but also think it's good to avoid mistakes when that kind of thing is concerned).

```
  PID User     Command                         Swap      USS      PSS      RSS 
19236 chia     chia_full_node                620152    49744   204360   581216 
20319 chia     chia_full_node                604684    65724   220111   596736 
 5009 chia     chia_full_node                379876   343772   456082   763932 
 4202 chia     chia_full_node                248624   577972   688631   993132
```

**Reply by caeci11ius** [reply]
Have just tried adding reserved_cores: 1 to config.yaml and am still spawning four instances. Is this the minimum, or is the setting not working?

```
full_node:
  database_path: db/blockchain_v1_CHALLENGE.sqlite
  dns_servers:
  - dns-introducer.chia.net
  enable_profiler: false
  enable_upnp: false
  exempt_peer_networks: []
  farmer_peer:
    host: 127.0.0.1
    port: 8447
  introducer_peer:
    host: introducer.chia.net
    port: 8444
  log_sqlite_cmds: false
  logging: *id001
  max_inbound_farmer: 10
  max_inbound_timelord: 5
  max_inbound_wallet: 20
  network_overrides: *id002
  peer_connect_interval: 30
  peer_connect_timeout: 30
  peer_db_path: db/peer_table_node.sqlite
  port: 8444
  recent_peer_threshold: 6000
  reserved_cores: 1
  rpc_port: 8555
  sanitize_weight_proof_only: false
  selected_network: mainnet
  send_uncompact_interval: 0
  short_sync_blocks_behind_threshold: 20
  simulator_database_path: sim_db/simulator_blockchain_v1_CHALLENGE.sqlite
  simulator_peer_db_path: sim_db/peer_table_node.sqlite
  ssl:
    private_crt: config/ssl/full_node/private_full_node.crt
    private_key: config/ssl/full_node/private_full_node.key
    public_crt: config/ssl/full_node/public_full_node.crt
    public_key: config/ssl/full_node/public_full_node.key
  start_rpc_server: true
  sync_blocks_behind_threshold: 300
  target_outbound_peer_count: 8
  target_peer_count: 80
  target_uncompact_proofs: 100
  timelord_peer:
    host: 127.0.0.1
    port: 8446
  wallet_peer:
    host: 127.0.0.1
    port: 8449
  weight_proof_timeout: 360
```
