### ISSUE TITLE
[Bug] Issues with harvester with hundreds of disks

### ISSUE THREAD

**Issue by 0X1231** [Chia-Network/chia-blockchain#11225]
### What happened?

I hope the government will pay attention. Now there are many large-scale farmers who are becoming no-node farmers, because the efficiency of the harvester is too low. For example, I have 100-200 hard disks on a computer. If I only open one harvester, the harvester will not work. It keeps restarting with errors.
Efficiency is slow. Even without computing power output. So I chose hpool and became a nodeless miner with the disk sweeping tool they provided. This goes against my blockchain beliefs, but the reality is that the harvester is too difficult to use.
Is it possible to consider that multiple harvesters can be opened on one computer, so that one harvester is only responsible for part of the disk?

### Version

1.3.4

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by jmhands** [comment]
we have profiled 300+ drives on a single harvester instance with consistent lookup times of 1.2 seconds. There are multiple improvements coming with commits already in main branch, but the workaround for now is to set plot loading frequency very high if you are not plotting anymore

**Comment by chiavivi** [comment]
绘图加载频率设置得非常高，在什么地方设置

**Comment by 0X1231** [comment]
> 我们已经在单个收割机实例上分析了300多个驱动器，一致的查找时间为1.2秒。主分支中已有的提交带来了许多改进，但现在的解决方法是，如果您不再进行绘图，则将绘图加载频率设置得非常高

具体是需要怎么做？安装1.3.4可以解决吗？

**Comment by 0X1231** [comment]
建议收割机的设计上能充分利用CPU的资源来读取硬盘，放着大把的系统资源无法利用，收割100张磁盘就开始效率低下。

**Comment by emlowe** [comment]
We have some more improvements coming in a later release after 1.3.4 - what JM was suggesting was to set the following in config.yaml:

```
harvester:
  plots_refresh_parameter:
    interval_seconds: 120 # The interval in seconds to refresh the plot file manager
    retry_invalid_seconds: 1200 # How long to wait before re-trying plots which failed to load
    batch_size: 300 # How many plot files the harvester processes before it waits batch_sleep_milliseconds
    batch_sleep_milliseconds: 1 # Milliseconds the harvester sleeps between batch processing
```

You can set the `interval_seconds` to a very large number like 86400 which will refresh the plot list 1x a day.  Obviously, if you are actively plotting, this means new plots will show up only after a day. You probably don't need to adjust the other parameters.
