### ISSUE TITLE
wallet database_path and can I delete blockchain_wallet_v1_mainnet_1_xxxxx.sqlite after db upgrade to v2 

### ISSUE THREAD

**Issue by limonatadipesce** [Chia-Network/chia-blockchain#11286]
### What happened?

Hi,

I upgraded from 1.2.11 to 1.3.4 including a `chia db upgrade`. 
In config.yaml `full_node: database_path:` points to `db/blockchain_v2_CHALLENGE.sqlite`. I removed the old big 
`.chia/mainnet/db/blockchain_v1_mainnet.sqlite` file. Seems to work.

But in **wallet directory**  `.chia/mainnet/wallet/db` I do see a `blockchain_wallet_v1_mainnet_xxxx.sqlite` file (12 GB size) and a smaller `blockchain_wallet_v2_mainnet_xxxx.sqlite` (just 15 MB) file. Can I remove `blockchain_wallet_v1_mainnet_xxxx.sqlite`, which doesn't change size or time stamp, while  `blockchain_wallet_v2_mainnet_xxxx.sqlite` is changing.

And in `config.yaml` in the `wallet:` section the `database_path` points to v1 version, where as in the `full_node:` section the `database_path` has been changed to `db/blockchain_v2_CHALLENGE.sqlite` by running `chia db upgrade`. I don't understand that.

```
wallet:
  database_path: wallet/db/blockchain_wallet_v1_CHALLENGE_KEY.sqlite
  full_node_peer:
    host: localhost
    port: 8444
```

Ciao!

### Version

1.3.4

### What platform are you using?

Linux

### What ui mode are you using?

CLI
