### ISSUE TITLE
[Bug] 2.0 RC2 Start Harvester Fails

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chia-blockchain#15910]
### What happened?
Bug reported by Daryl in Discord (https://discord.com/channels/1034523881404370984/1099818017908592660/1135638423118549083)

Updated from the first 2.0 alpha release to the 2.0 rc2 release, but it keeps throwing an error when I try to start the harvester.

![image](https://github.com/Chia-Network/chia-blockchain/assets/48610606/71f01e4c-048f-4ddb-9730-f15395747e0e)

Attempted resolutions:
- Deleted config and started fresh
- enabled gpu decompression
- set parallel decompressor threads to 1. 
- Threads were at 8, tried to bump them down to 1, no such luck
- updated and upgraded all my packages, then restarted to make sure something wasn't hanging on to the GPU or something. Just won't start the harvester
- Only way to get around the error was to rename it back to decompresser (from decompressor), but then GPU farming wasn't working

More info:
Nvidia Driver: 530.30.02
CUDA Version: 12.1
Ubuntu desktop, 40 cores with 256GB of RAM, RTX a4000

Steps to reproduce:
- Close gui
- Chia stop all -d
- backup config file to desktop
- delete config file
- sudo dpkg --install chia-blockchain_2.0.0rc2_amd64.deb
- chia init
- set parallel_decompressor_count to 1
- add plot directories
- switch use_gpu_harvesting to true
- run chia start harvester

Config file harvester section:
```
harvester:
  chia_ssl_ca:
    crt: config/ssl/ca/chia_ca.crt
    key: config/ssl/ca/chia_ca.key
  decompressor_thread_count: 0
  disable_cpu_affinity: false
  enforce_gpu_index: false
  farmer_peer:
    host: localhost
    port: 8447
  gpu_index: 0
  logging: *id001
  max_compression_level_allowed: 7
  network_overrides: *id002
  num_threads: 30
  parallel_decompressor_count: 1
  parallel_read: true
  plot_directories:
  - /mnt/j301
  plots_refresh_parameter:
    batch_size: 300
    batch_sleep_milliseconds: 1
    interval_seconds: 120
    retry_invalid_seconds: 1200
  port: 8448
  private_ssl_ca:
    crt: config/ssl/ca/private_ca.crt
    key: config/ssl/ca/private_ca.key
  recursive_plot_scan: false
  rpc_port: 8560
  selected_network: mainnet
  ssl:
    private_crt: config/ssl/harvester/private_harvester.crt
    private_key: config/ssl/harvester/private_harvester.key
  start_rpc_server: true
  use_gpu_harvesting: true
  ```

### Version

2.0 RC2

### What platform are you using?

Linux

### What ui mode are you using?

CLI
