### ISSUE TITLE
[BUG] per service logging settings are ignored

### ISSUE THREAD

**Issue by felixbrucker** [Chia-Network/chia-blockchain#485]
**Describe the bug**
With beta 16 setting the logging settings for some service only, like harvester, does not apply them. Instead the root logging settings are used (root `logging` key of the config file).

**To Reproduce**

0. Use the default config of `chia init`
1. Modify eg. the harvester logging option to the following:
```
  logging:
    log_filename: log/harvester.log
    log_level: INFO
    log_stdout: false
```
2. Observe no output in the `harvester.log` file (and its also not even created)

**Expected behavior**

Same as with beta 15: the logging settings of the service are used.

**Desktop (please complete the following information):**

- OS: Windows
- OS Version/Flavor: 10
- CPU: doesn't matter
