### ISSUE TITLE
[BUG] Update 1.6 old plots are not valid any more

### ISSUE THREAD

**Issue by 321SK** [Chia-Network/chia-blockchain#5708]
After update to version 1.6 on Windows just a view plots form the last two days are working.
All other about 150 Plots since the start of Chia are not working. 

Are the old plots working any more?

What can I do?

config.yaml -> plot directories, maybe something wrong I can't see?

```
farmer_peer:
    host: localhost
    port: 8447
  logging: *id001
  network_overrides: *id002
  num_threads: 30
  plot_directories:
  - D:\
  - E:\
  plot_loading_frequency_seconds: 120
  port: 8448
  private_ssl_ca:
    crt: config/ssl/ca/private_ca.crt
    key: config/ssl/ca/private_ca.key
  rpc_port: 8560
  selected_network: mainnet
```

- I have deinstalled the chia wallet and installed new same problem.
- Tried version 1.5 -> same problem.
- Reinstall version 1.6 ->same problem.
- edited config directories ->same problem.

= Chia 1.6 -> only new plots form yesterday are working :-(

==> for now I'm using hpool this works :-)
===> waiting for version 1.7 or a good hint to solve the problem
