### ISSUE TITLE
[BUG] chia init does not fully migrate config.yaml to 1.1.6

### ISSUE THREAD

**Issue by jcasc** [Chia-Network/chia-blockchain#5748]
When upgrading to 1.1.6 and running chia init, the config will still miss:

```
    log_maxfilesrotation: 7
```

```
  dns_servers:
  - dns-introducer.chia.net
  enable_profiler: false
   ...
  exempt_peer_networks: []

```

```
      testnet7:
        DIFFICULTY_CONSTANT_FACTOR: 10052721566054
        DIFFICULTY_STARTING: 30
        EPOCH_BLOCKS: 768
        GENESIS_CHALLENGE: 117816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015af
        GENESIS_PRE_FARM_FARMER_PUZZLE_HASH: 3d8765d3a597ec1d99663f6c9816d915b9f68613ac94009884c4addaefcce6af
        GENESIS_PRE_FARM_POOL_PUZZLE_HASH: d23da14695a188ae5708dd152263c4db883eb27edeb936178d4d988b8f3ce5fc
        INITIAL_FREEZE_END_TIMESTAMP: 1619661600
        MEMPOOL_BLOCK_BUFFER: 10
        MIN_PLOT_SIZE: 18
        NETWORK_TYPE: 1
```
(which is why `chia configure -t true; chia whatever` will fail with a missing-dict-key error.)

and possible more settings that I overlooked.

Some  default settings will also of course not be set to their new value, such as `  weight_proof_timeout: 360` , but I assume this is intended as it cannot be known whether the user set those deliberately or not.
