### ISSUE TITLE
[BUG] port 8444 cannot be changed

### ISSUE THREAD

**Issue by dimitrus** [Chia-Network/chia-blockchain#6430]
Please check, port 8444 cannot be changed, it is hardcoded somewhere. 
If you change to port 10444, port 8444 will be visible everywhere(gui, log, cli). 

```
(venv) user@harvester:/opt/chia-blockchain$ netstat -n4|grep 10444
tcp        0      0 127.0.0.1:37688         127.0.0.1:10444         ESTABLISHED
tcp        0      0 192.168.1.110:10444     58.136.1.10:52503       ESTABLISHED
tcp        0      0 127.0.0.1:10444         127.0.0.1:37688         ESTABLISHED
tcp        0      0 192.168.1.110:10444     89.65.255.172:52110     ESTABLISHED

```
`(venv) user@harvester:/opt/chia-blockchain$ chia show -c|grep 10444`
                                                                                                                     
```
(venv) user@harvester:/opt/chia-blockchain$ chia show -c|grep 58.136.1.10
FULL_NODE 58.136.1.10                            52503/8444  b0f27547... Jun 05 11:28:51      2.1|0.2    
```

```
(venv) user@harvester:/opt/chia-blockchain$ chia show -c|grep 89.65.255.172
FULL_NODE 89.65.255.172                          52110/8444  b1ffb604... Jun 05 11:00:44      0.1|0.0    
```
```
Connections:
Type      IP                                 Ports(src/dst)  NodeID      Last Connect      MiB Up|Dwn
{'bytes_read': 50, 'bytes_written': 36940, 'creation_time': 1622888262.3994195, 'last_message_time': 1622888262.3996558, 'local_port': 10444, 'node_id': b'blablabla', 'peak_hash': None, 'peak_height': None, 'peak_weight': None, 'peer_host': '127.0.0.1', 'peer_port': 51994, 'peer_server_port': 8447, 'type': 3}
FARMER    127.0.0.1                              51994/8447  2208708c... Jun 05 13:17:42      0.0|0.0    
{'bytes_read': 1694, 'bytes_written': 564635, 'creation_time': 1622888262.9870434, 'last_message_time': 1622891149.942424, 'local_port': 10444, 'node_id': b'blablabla', 'peak_hash': None, 'peak_height': None, 'peak_weight': None, 'peer_host': '127.0.0.1', 'peer_port': 51998, 'peer_server_port': 8449, 'type': 6}
WALLET    127.0.0.1                              51998/8449  1d4783f4... Jun 05 14:05:49      0.5|0.0    
{'bytes_read': 133162, 'bytes_written': 15473848, 'creation_time': 1622888274.263274, 'last_message_time': 1622891179.042559, 'local_port': 10444, 'node_id': b'blablabla', 'peak_hash': '0xblablabla', 'peak_height': 225758, 'peak_weight': 6252102, 'peer_host': '188.244.143.201', 'peer_port': 8444, 'peer_server_port': 8444, 'type': 1}
FULL_NODE 188.244.143.201                         8444/8444  3acf6c90... Jun 05 14:06:19     14.8|0.1    
                                                 -SB Height:   225758    -Hash: 2d39dcfe...
{'bytes_read': 528109, 'bytes_written': 320425, 'creation_time': 1622888325.8847373, 'last_message_time': 1622891182.6956375, 'local_port': 10444, 'node_id': b'blablabla', 'peak_hash': '0xblablabla', 'peak_height': 387351, 'peak_weight': 96513832, 'peer_host': '104.11.247.24', 'peer_port': 8444, 'peer_server_port': 8444, 'type': 1}
FULL_NODE 104.11.247.24                           8444/8444  bd4a501f... Jun 05 14:06:22      0.3|0.5    
                                                 -SB Height:   387351    -Hash: ed6d6fd9...
```
### config.yaml:
```
full_node:
  database_path: db/blockchain_v1_CHALLENGE.sqlite
  enable_upnp: false
  farmer_peer:
    host: localhost
    port: 8447
  introducer_peer:
    host: introducer-eu.chia.net
    port: 8444
  logging:
    log_filename: log/node.log
    log_level: DEBUG
    log_maxfilesrotation: 7
    log_stdout: false
  max_inbound_farmer: 10
  max_inbound_timelord: 5
  max_inbound_wallet: 20
  network_overrides: *id002
  peer_connect_interval: 30
  peer_db_path: db/peer_table_node.sqlite
  port: 10444
  recent_peer_threshold: 6000
  rpc_port: 8555
  sanitize_weight_proof_only: false
  selected_network: mainnet
  send_uncompact_interval: 0
  short_sync_blocks_behind_threshold: 20
  simulator_database_path: sim_db/simulator_blockchain_v1_CHALLENGE.sqlite
  simulator_peer_db_path: sim_db/peer_table_node.sqlite
  ssl:
    private_crt: config/ssl/full_node/private_full_node.crt
    private_key: config/ssl/full_node/private_full_node.key
    public_crt: config/ssl/full_node/public_full_node.crt
    public_key: config/ssl/full_node/public_full_node.key
  start_rpc_server: true
  sync_blocks_behind_threshold: 300
  target_outbound_peer_count: 30
  target_peer_count: 80
  target_uncompact_proofs: 100
  timelord_peer:
    host: localhost
    port: 8446
  wallet_peer:
    host: localhost
    port: 8449
  weight_proof_timeout: 360
```
