### ISSUE TITLE
[BUG] Harvester looks up 'host' just once.

### ISSUE THREAD

**Issue by Knight1** [Chia-Network/chia-blockchain#7648]
**Describe the bug**

Harvester looks up host just once. If the dynamic IP @ home changes harvester does not reconnect to new IP Address.

```
harvester:
  chia_ssl_ca:
    crt: config/ssl/ca/chia_ca.crt
    key: config/ssl/ca/chia_ca.key
  farmer_peer:
    host: [remote DNS Name with changing IP]
    port: 8447
```

**To Reproduce**

1. Setup Full node with Internet @ home where the IP changes after each reconnect.
2. Setup remote Farmer node to use an external DNS (dyndns) service for changing IPs ex. noip.com
3. Change IP
4. Harvester will still use old IP after hours.

**Expected behavior**
Harvester looks up IP every x Minutes or use ex. gethostbyaddr and notices the change and use the new IP address.

**Desktop**

- OS: Linux
- OS Version/Flavor: Debian
- CPU: AMD Ryzen 9 5950X
