### ISSUE TITLE
[BUG] pay address was wrong when using the pool protocal

### ISSUE THREAD

**Issue by JsBlueCat** [Chia-Network/chia-blockchain#7827]
$ chia wallet get_address
xch1p8y2h7kvmk558q4zuphc3hwpa3z5z9y49qdzzkhqup4tkqatnd6svtywt4

the address got is different with which in my config.yaml

**Comment by DrakeFS** [comment]
`chia wallet get_address` will only show the last created public receive address for said wallet.  Wallets can and will have multiple public receive addresses.  Every time you create a new NFT it will create a new public receive address.

> the address got is different with which in my config.yaml

```
pool:
  logging: *id001
  network_overrides: *id002
  pool_list:
  - authentication_public_key: 
    launcher_id: 
    owner_public_key: 
    p2_singleton_puzzle_hash: 
    payout_instructions:
    pool_url: 
    target_puzzle_hash: 
  selected_network: 
  xch_target_address:
```

The lines that have you payout instructions are `payout_instructions` (pool payouts) and `xch_target_address` (farmer rewards)

You will need to use a puzzle hash converter (like the one found on [Chia Explorer](https://www.chiaexplorer.com/tools/address-puzzlehash-converter)) the convert the `payout_instructions` to an XCHaddress
