### ISSUE TITLE
How can I use the GUI to show the status of a remote farmer?

### ISSUE THREAD

**Issue by yjiangnan** [Chia-Network/chia-blockchain#8155]
### Discussed in https://github.com/Chia-Network/chia-blockchain/discussions/8154

<div type='discussions-op-text'>

<sup>Originally posted by **yjiangnan** August 22, 2021</sup>
As far as I can understand, the GUI normally receives the farmer status (especially the information in the table Last Attempted Proof in tab Farm of the GUI interface) by connecting to daemon and port by websocket "wss://localhost:55400". I am trying to view the farming status remotely by changing the daemon host, port and ssl keys in my  local GUI configuration file `~/.chia/mainnet/config/config.yaml`:
```
ui:
  daemon_host: remote.host.domain
  daemon_port: 55000
  daemon_ssl:
    private_crt: config/ssl/remote_daemon/private_daemon.crt
    private_key: config/ssl/remote_daemon/private_daemon.key
```
in which the `remote_daemon` is downloaded from `~/.chia/mainnet/config/ssl/daemon` on the remote host. The remote host daemon port has been changed to 55000 and port-forwarded on the router. The remote daemon has been restarted. 

However, when I restart my local GUI, the program is stuck on the page of `Connecting to wallet` and the top of the program shows `Chia Blockchain [wss://remote.host.domain:55000]` indicating that the connection cannot be established. So, how can I get it to work? Thanks!</div>
